apiVersion: v1
kind: Pod
spec:
  # Ensure we only schedule on nodes with a t4 GPU
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-t4
  containers:
    - name: devpod
      resources:
        requests:
          nvidia.com/gpu: "1"
        limits:
          nvidia.com/gpu: "1"
  # tolerations will be added automatically by GKE
  # otherwise would need to add
  #
  # tolerations:
  # - effect: NoSchedule
  #   key: nvidia.com/gpu
  #   operator: Exists
